sliply_project/urls.py
import registration
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token

from sliply.views import FileUploadView, SlipListView, SlipDetailView, SlipUpdateView, SlipDeleteView, SearchView, \
    UserProfileView, UserUpdateView, ItemListView, ItemDetailView, SlipCreateView, ItemUpdateView, ItemDeleteView, \
    ItemCreateView
from sliply_api.views import SlipListViewAPI
from sliply_project.settings import DEBUG, MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', UserProfileView.as_view(), name='main'),
    url(r'^upload/$', FileUploadView.as_view(), name='upload'),
    url(r'^login/$', auth_views.login, {'redirect_field_name': 'next'}, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^auth/', include('rest_framework_social_oauth2.urls')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^slips/$', SlipListView.as_view(), name='slips'),
    url(r'^slips/create/$', SlipCreateView.as_view(), name='slip_create'),
    url(r'^slips/(?P<pk>(\d)+)/$', SlipDetailView.as_view(), name='slip_details'),
    url(r'^slips/(?P<pk>(\d)+)/edit/$', SlipUpdateView.as_view(), name='slip_edit'),
    url(r'^slips/(?P<pk>(\d)+)/delete/$', SlipDeleteView.as_view(), name='slip_delete'),
    url(r'^slips/search/$', SearchView.as_view(), name='slips_search'),
    url(r'^items/$', ItemListView.as_view(), name='items'),
    url(r'^items/(?P<pk>(\d)+)/$', ItemDetailView.as_view(), name='item_details'),
    url(r'^items/(?P<pk>(\d)+)/edit/$', ItemUpdateView.as_view(), name='item_edit'),
    url(r'^items/(?P<pk>(\d)+)/delete/$', ItemDeleteView.as_view(), name='item_delete'),
    url(r'^items/create/$', ItemCreateView.as_view(), name='item_create'),
    url(r'^profile/$', UserProfileView.as_view(), name='profile_details'),
    url(r'^profile/(?P<pk>(\d)+)/edit/$', UserUpdateView.as_view(), name='profile_edit'),
    url(r'^api/$', SlipListViewAPI.as_view(), name='slip_api'),
    url(r'^api-token-auth/', obtain_jwt_token),
    url(r'^api-token-refresh/', refresh_jwt_token),
]

if DEBUG is True:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

sliply/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls.base import reverse


PAYMENT_TYPES = (
    (0, 'Cash'),
    (1, 'Card'),
    (2, 'Other'),
)

class Slip(models.Model):
    owner = models.ForeignKey(User, null=True, blank=True)
    scanfile = models.FileField()
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    raw_text = models.TextField(null=True, blank=True)
    seller_name = models.CharField(max_length=255, null=True, blank=True)
    purchase_date = models.DateField(null=True, blank=True)
    total_amount = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    payment_type = models.SmallIntegerField(choices=PAYMENT_TYPES, null=True)

    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        return reverse('slip_details', kwargs = {'pk': self.pk})


class Item(models.Model):
    owner = models.ForeignKey(User, null=True, blank=True)
    slip = models.ForeignKey(Slip)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    raw_text = models.TextField(null=True, blank=True)
    item_name = models.CharField(max_length=128, null=True, blank=True)
    quantity = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    price = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)

    def __str__(self):
        return self.item_name

    def get_absolute_url(self):
        return reverse('item_details', kwargs = {'pk': self.pk})

sliply/forms.py
from django import forms

from .validators import validate_image_extension
from .models import Item, Slip


class UploadForm(forms.ModelForm):
    scanfile = forms.FileField(label='Add files to scan',
                               validators=[validate_image_extension, ],
                               widget=forms.ClearableFileInput(attrs={'multiple': True}))

    class Meta:
        model = Slip
        fields = ('scanfile',)


class SlipCreateForm(forms.ModelForm):
    purchase_date = forms.DateField(widget=forms.SelectDateWidget)

    class Meta:
        model = Slip
        exclude = ('owner', 'scanfile', 'raw_text')


class ItemCreateForm(forms.ModelForm):
    class Meta:
        model = Item
        exclude = ('owner', 'raw_text')

sliply/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db.models.aggregates import Sum
from django.db.models.query_utils import Q
from django.shortcuts import redirect, get_object_or_404
from django.urls.base import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from registration.views import RegistrationView
from rest_framework.authtoken.models import Token

from sliply_project.settings import MEDIA_URL
from .models import Slip, Item
from .tasks import parse_text, detect_text
from .forms import UploadForm, SlipCreateForm, ItemCreateForm

#Slip views

class FileUploadView(LoginRequiredMixin, CreateView):
    form_class = UploadForm
    template_name = 'form.html'

    def form_valid(self, form):
        files = self.request.FILES.getlist('scanfile')
        for n in range(0, len(files)):
            filename = files[n]
            owner = self.request.user
            save_to_db = Slip.objects.create(owner=owner, scanfile=filename)
            detect_text.delay(filename.name, save_to_db.pk)
        return redirect('slips')


class SlipListView(LoginRequiredMixin, ListView):
    def get_queryset(self):
        queryset = Slip.objects.filter(owner=self.request.user).order_by('-create_date')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = self.get_queryset()
        total_amount = queryset.aggregate(Sum('total_amount'))
        context['total_amount_sum'] = total_amount['total_amount__sum']
        return context


class SlipDetailView(LoginRequiredMixin, DetailView):
    queryset = Slip.objects.all()

    def get_context_data(self, **kwargs):
        get_action = self.request.GET.get('action')
        if get_action == 'rescan':
            parse_text.delay(self.object.raw_text, self.object.pk, get_action)
            messages.add_message(self.request, messages.INFO, "Processing text detection...")
        context = super().get_context_data(**kwargs)
        context['path'] = MEDIA_URL
        return context


class SlipUpdateView(LoginRequiredMixin, UpdateView):
    model = Slip
    fields = ('purchase_date', 'seller_name', 'total_amount', 'payment_type', 'raw_text')


class SlipDeleteView(LoginRequiredMixin, DeleteView):
    model = Slip
    success_url = reverse_lazy('slips')


class SearchView(SlipListView):
    def get_queryset(self):
        query = self.request.GET.get('query', default="")
        fromto = self.request.GET.get('fromto', default="")
        fromdate = self.request.GET.get('from', default="")
        todate = self.request.GET.get('to', default="")

        queryset = Slip.objects.filter(owner=self.request.user).order_by('-create_date').\
                       filter(seller_name__icontains=query) or \
                   Slip.objects.filter(owner=self.request.user).order_by('-create_date').\
                       filter(item__item_name__icontains=query)
        if fromto == "from" and fromdate != "" and todate!="":
            queryset = queryset.filter(Q(purchase_date__gte=fromdate)& Q(purchase_date__lte=todate))

        if fromto == "from" and fromdate != "" and todate == "":
            queryset = queryset.filter(purchase_date=fromdate)

        if fromto == "date" and fromdate != "":
            queryset = queryset.filter(purchase_date=fromdate)

        return queryset


class SlipCreateView(LoginRequiredMixin, CreateView):
        form_class = SlipCreateForm
        template_name = 'form.html'

        def form_valid(self, form):
            form_to_save = form.save(commit=False)
            form_to_save.owner = self.request.user
            form_to_save.save()
            return redirect('slips')

#Item views

class ItemListView(LoginRequiredMixin, ListView):
    def get_queryset(self):
        query = self.request.GET.get('query', default="")
        fromto = self.request.GET.get('fromto', default="")
        fromdate = self.request.GET.get('from', default="")
        todate = self.request.GET.get('to', default="")

        queryset = Item.objects.filter(owner=self.request.user).order_by('-create_date').\
                       filter(slip__seller_name__icontains=query) or \
                   Item.objects.filter(owner=self.request.user).order_by('-create_date').\
                       filter(item__icontains=query)

        if fromto == "from" and fromdate != "" and todate!="":
            queryset = queryset.filter(Q(slip__purchase_date__gte=fromdate)& Q(slip__purchase_date__lte=todate))

        if fromto == "from" and fromdate != "" and todate == "":
            queryset = queryset.filter(slip__purchase_date=fromdate)

        if fromto == "date" and fromdate != "":
            queryset = queryset.filter(slip__purchase_date=fromdate)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = self.get_queryset()
        total_amount = queryset.aggregate(Sum('price'))
        context['total_amount_sum'] = total_amount['price__sum']
        return context


class ItemDetailView(LoginRequiredMixin, DetailView):
    model = Item


class ItemUpdateView(LoginRequiredMixin, UpdateView):
    model = Item
    template_name = 'sliply/slip_form.html'
    fields = ('item_name', 'quantity', 'price', 'raw_text')


class ItemDeleteView(LoginRequiredMixin, DeleteView):
    model = Item
    template_name = 'sliply/slip_confirm_delete.html'
    success_url = reverse_lazy('items')


class ItemCreateView(LoginRequiredMixin, CreateView):
    form_class = ItemCreateForm
    template_name = 'form.html'

    def form_valid(self, form):
        form_to_save = form.save(commit=False)
        form_to_save.owner = self.request.user
        form_to_save.save()
        return redirect('items')

#User views

class UserProfileView(LoginRequiredMixin, DetailView):

    def get_object(self):
        return get_object_or_404(User, pk=self.request.user.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_token = Token.objects.get_or_create(user=self.request.user)
        context['token'] = user_token
        return context

class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    fields = ('username', 'first_name', 'last_name', 'email')
    success_url = reverse_lazy('profile_details')

sliply/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% include 'snippets/head.html' %}
    <title>{% block title %}Sliply{% endblock %}</title>
</head>
<body>

<div class="container-fluid">
    <div class="row">
        <div class="col-3 col-md-2 Sidebar sticky-top">
            {% include 'menu.html' %}
        </div>
        <div class="col-9 col-md-10 bg-grey Main">
            {% if messages %}
                <div class="container-fluid">
                    {% for message in messages %}
                        <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
            <div class="container-fluid">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</div>
{% include 'snippets/script_bottom.html' %}
</body>
</html>

sliply/templates/form.html
{% extends 'subbase.html' %}
{% block cardheader %}
{% endblock %}
{% block form %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
{{ form.as_p }}
      <button type="submit">Save</button>
  </form>
{% endblock %}

sliply/templates/menu.html
<div class="d-flex p-3 justify-content-center ">
    <div id="circle" class="bg-secondary">
        <a href="#" data-toggle="dropdown" style="color: white; text-decoration: none; letter-spacing: -0.3vw;">
        {% if request.user.first_name  %}
            {{ request.user.first_name.0 }}{{ request.user.last_name.0 }}
        {% else %}
            {{ request.user.username.0 }}
        {% endif %}
        </a>
        <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'profile_details' %}">
                Profile details
            </a>
            <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
        </div>
    </div>
</div>

<div class="list-group">
    <a href="#drop_address" class="list-group-item list-group-item-action list-group-item-secondary"
       data-toggle="collapse">
        <i class="far fa-file-alt fa-lg"></i> Slips
        <span class="badge badge-info">{{ request.user.slip_set.count }}</span></a>
    <div id="drop_address" class="collapse">
        <a href="{% url 'slips' %}" class="list-group-item list-group-item-action" id="dropmenu">
            Search
        </a>
        <a href="{% url 'slip_create' %}" class="list-group-item list-group-item-action" id="dropmenu">
            Create a slip
        </a>
    </div>

    <a href="#drop_group" class="list-group-item list-group-item-action list-group-item-secondary"
       data-toggle="collapse">
        <i class="fas fa-shopping-basket fa-lg"></i> Items <span
            class="badge badge-info">{{ request.user.item_set.count }}</span></a>

    <div id="drop_group" class="collapse">
        <a href="{% url 'items' %}" class="list-group-item list-group-item-action" id="dropmenu">
            Search
        </a>
        <a href="{% url 'item_create' %}" class="list-group-item list-group-item-action" id="dropmenu">
            Add an item
        </a>
    </div>

    <a href="{% url 'upload' %}" class="list-group-item list-group-item-action list-group-item-secondary">
        <i class="fas fa-plus"></i> Add a scan</a>

</div>

sliply/templates/subbase.html
{% extends 'base.html' %}
{% block content %}
    <div class="d-flex pt-4 justify-content-center">
        <div class="card" style="width: 90vw">
            <div class="card-header">
             {% block cardheader %}
             {% endblock %}
            </div>
            <div class="card-body">
            {% block form %}
            {% endblock %}
            </div>
        </div>
    </div>
{% endblock %}