sliply_project/urls.py
import registration
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token

from sliply.views import FileUploadView, SlipListView, SlipDetailView, SlipUpdateView, SlipDeleteView, SearchView, \
    UserProfileView, UserUpdateView, ItemListView, ItemDetailView, SlipCreateView, ItemUpdateView, ItemDeleteView, \
    ItemCreateView
from sliply_api.views import SlipListViewAPI
from sliply_project.settings import DEBUG, MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', UserProfileView.as_view(), name='main'),
    url(r'^upload/$', FileUploadView.as_view(), name='upload'),
    url(r'^login/$', auth_views.login, {'redirect_field_name': 'next'}, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^auth/', include('rest_framework_social_oauth2.urls')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^slips/$', SlipListView.as_view(), name='slips'),
    url(r'^slips/create/$', SlipCreateView.as_view(), name='slip_create'),
    url(r'^slips/(?P<pk>(\d)+)/$', SlipDetailView.as_view(), name='slip_details'),
    url(r'^slips/(?P<pk>(\d)+)/edit/$', SlipUpdateView.as_view(), name='slip_edit'),
    url(r'^slips/(?P<pk>(\d)+)/delete/$', SlipDeleteView.as_view(), name='slip_delete'),
    url(r'^slips/search/$', SearchView.as_view(), name='slips_search'),
    url(r'^items/$', ItemListView.as_view(), name='items'),
    url(r'^items/(?P<pk>(\d)+)/$', ItemDetailView.as_view(), name='item_details'),
    url(r'^items/(?P<pk>(\d)+)/edit/$', ItemUpdateView.as_view(), name='item_edit'),
    url(r'^items/(?P<pk>(\d)+)/delete/$', ItemDeleteView.as_view(), name='item_delete'),
    url(r'^items/create/$', ItemCreateView.as_view(), name='item_create'),
    url(r'^profile/$', UserProfileView.as_view(), name='profile_details'),
    url(r'^profile/(?P<pk>(\d)+)/edit/$', UserUpdateView.as_view(), name='profile_edit'),
    url(r'^api/$', SlipListViewAPI.as_view(), name='slip_api'),
    url(r'^api-token-auth/', obtain_jwt_token),
    url(r'^api-token-refresh/', refresh_jwt_token),
]

if DEBUG is True:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

sliply/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls.base import reverse


PAYMENT_TYPES = (
    (0, 'Cash'),
    (1, 'Card'),
    (2, 'Other'),
)

class Slip(models.Model):
    owner = models.ForeignKey(User, null=True, blank=True)
    scanfile = models.FileField()
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    raw_text = models.TextField(null=True, blank=True)
    seller_name = models.CharField(max_length=255, null=True, blank=True)
    purchase_date = models.DateField(null=True, blank=True)
    total_amount = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    payment_type = models.SmallIntegerField(choices=PAYMENT_TYPES, null=True)

    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        return reverse('slip_details', kwargs = {'pk': self.pk})


class Item(models.Model):
    owner = models.ForeignKey(User, null=True, blank=True)
    slip = models.ForeignKey(Slip)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    raw_text = models.TextField(null=True, blank=True)
    item_name = models.CharField(max_length=128, null=True, blank=True)
    quantity = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    price = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)

    def __str__(self):
        return self.item_name

    def get_absolute_url(self):
        return reverse('item_details', kwargs = {'pk': self.pk})

sliply/forms.py
from django import forms

from .validators import validate_image_extension
from .models import Item, Slip


class UploadForm(forms.ModelForm):
    scanfile = forms.FileField(label='Add files to scan',
                               validators=[validate_image_extension, ],
                               widget=forms.ClearableFileInput(attrs={'multiple': True}))

    class Meta:
        model = Slip
        fields = ('scanfile',)


class SlipCreateForm(forms.ModelForm):
    purchase_date = forms.DateField(widget=forms.SelectDateWidget)

    class Meta:
        model = Slip
        exclude = ('owner', 'scanfile', 'raw_text')


class ItemCreateForm(forms.ModelForm):
    class Meta:
        model = Item
        exclude = ('owner', 'raw_text')

sliply/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db.models.aggregates import Sum
from django.db.models.query_utils import Q
from django.shortcuts import redirect, get_object_or_404
from django.urls.base import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from registration.views import RegistrationView
from rest_framework.authtoken.models import Token

from sliply_project.settings import MEDIA_URL
from .models import Slip, Item
from .tasks import parse_text, detect_text
from .forms import UploadForm, SlipCreateForm, ItemCreateForm

#Slip views

class FileUploadView(LoginRequiredMixin, CreateView):
    form_class = UploadForm
    template_name = 'form.html'

    def form_valid(self, form):
        files = self.request.FILES.getlist('scanfile')
        for n in range(0, len(files)):
            filename = files[n]
            owner = self.request.user
            save_to_db = Slip.objects.create(owner=owner, scanfile=filename)
            detect_text.delay(filename.name, save_to_db.pk)
        return redirect('slips')


class SlipListView(LoginRequiredMixin, ListView):
    def get_queryset(self):
        queryset = Slip.objects.filter(owner=self.request.user).order_by('-create_date')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = self.get_queryset()
        total_amount = queryset.aggregate(Sum('total_amount'))
        context['total_amount_sum'] = total_amount['total_amount__sum']
        return context


class SlipDetailView(LoginRequiredMixin, DetailView):
    queryset = Slip.objects.all()

    def get_context_data(self, **kwargs):
        get_action = self.request.GET.get('action')
        if get_action == 'rescan':
            parse_text.delay(self.object.raw_text, self.object.pk, get_action)
            messages.add_message(self.request, messages.INFO, "Processing text detection...")
        context = super().get_context_data(**kwargs)
        context['path'] = MEDIA_URL
        return context


class SlipUpdateView(LoginRequiredMixin, UpdateView):
    model = Slip
    fields = ('purchase_date', 'seller_name', 'total_amount', 'payment_type', 'raw_text')


class SlipDeleteView(LoginRequiredMixin, DeleteView):
    model = Slip
    success_url = reverse_lazy('slips')


class SearchView(SlipListView):
    def get_queryset(self):
        query = self.request.GET.get('query', default="")
        fromto = self.request.GET.get('fromto', default="")
        fromdate = self.request.GET.get('from', default="")
        todate = self.request.GET.get('to', default="")

        queryset = Slip.objects.filter(owner=self.request.user).order_by('-create_date').\
                       filter(seller_name__icontains=query) or \
                   Slip.objects.filter(owner=self.request.user).order_by('-create_date').\
                       filter(item__item_name__icontains=query)
        if fromto == "from" and fromdate != "" and todate!="":
            queryset = queryset.filter(Q(purchase_date__gte=fromdate)& Q(purchase_date__lte=todate))

        if fromto == "from" and fromdate != "" and todate == "":
            queryset = queryset.filter(purchase_date=fromdate)

        if fromto == "date" and fromdate != "":
            queryset = queryset.filter(purchase_date=fromdate)

        return queryset


class SlipCreateView(LoginRequiredMixin, CreateView):
        form_class = SlipCreateForm
        template_name = 'form.html'

        def form_valid(self, form):
            form_to_save = form.save(commit=False)
            form_to_save.owner = self.request.user
            form_to_save.save()
            return redirect('slips')

#Item views

class ItemListView(LoginRequiredMixin, ListView):
    def get_queryset(self):
        query = self.request.GET.get('query', default="")
        fromto = self.request.GET.get('fromto', default="")
        fromdate = self.request.GET.get('from', default="")
        todate = self.request.GET.get('to', default="")

        queryset = Item.objects.filter(owner=self.request.user).order_by('-create_date').\
                       filter(slip__seller_name__icontains=query) or \
                   Item.objects.filter(owner=self.request.user).order_by('-create_date').\
                       filter(item__icontains=query)

        if fromto == "from" and fromdate != "" and todate!="":
            queryset = queryset.filter(Q(slip__purchase_date__gte=fromdate)& Q(slip__purchase_date__lte=todate))

        if fromto == "from" and fromdate != "" and todate == "":
            queryset = queryset.filter(slip__purchase_date=fromdate)

        if fromto == "date" and fromdate != "":
            queryset = queryset.filter(slip__purchase_date=fromdate)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = self.get_queryset()
        total_amount = queryset.aggregate(Sum('price'))
        context['total_amount_sum'] = total_amount['price__sum']
        return context


class ItemDetailView(LoginRequiredMixin, DetailView):
    model = Item


class ItemUpdateView(LoginRequiredMixin, UpdateView):
    model = Item
    template_name = 'sliply/slip_form.html'
    fields = ('item_name', 'quantity', 'price', 'raw_text')


class ItemDeleteView(LoginRequiredMixin, DeleteView):
    model = Item
    template_name = 'sliply/slip_confirm_delete.html'
    success_url = reverse_lazy('items')


class ItemCreateView(LoginRequiredMixin, CreateView):
    form_class = ItemCreateForm
    template_name = 'form.html'

    def form_valid(self, form):
        form_to_save = form.save(commit=False)
        form_to_save.owner = self.request.user
        form_to_save.save()
        return redirect('items')

#User views

class UserProfileView(LoginRequiredMixin, DetailView):

    def get_object(self):
        return get_object_or_404(User, pk=self.request.user.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_token = Token.objects.get_or_create(user=self.request.user)
        context['token'] = user_token
        return context

class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    fields = ('username', 'first_name', 'last_name', 'email')
    success_url = reverse_lazy('profile_details')

sliply/templates/sliply/item_detail.html
{% extends 'subbase.html' %}
{% block cardheader %}

    <a href="{% url 'item_edit' object.pk %}"><i class="fas fa-edit fa-lg"></i></a>
    <a href="{% url 'item_delete' object.pk %}"><i class="fas fa-trash-alt fa-lg"></i></a>
{% endblock %}
{% block form %}
    <div class="col">
        <div class="row">
            Item: {{ object.item_name }}
        </div>
        <div class="row">
            From: {{ object.slip.seller_name }}
        </div>
        <div class="row">
            Quantity: {{ object.quantity }}
        </div>
        <div class="row">
            Price: {{ object.price }}
        </div>


        {% if object.slip %}
            <div class="row">
                <strong>Belongs to slip: </strong>
                <a href="{% url 'slip_details' object.slip.pk %}">
                    #{{ object.slip.pk }} {{ object.slip.purchase_date }}</a>
            </div>
        {% endif %}
    </div>

{% endblock %}

sliply/templates/sliply/item_list.html
{% extends 'base.html' %}
{% block content %}
    <div class="d-flex pt-5 justify-content-center">
        <form action="{% url 'items' %}" class="form-inline">
            <input type="text" id="searchinput" name="query" class="form-control form-control-lg"
                   placeholder="Search"
                   value="{{ request.GET.query }}">
            <select name="fromto" class="form-control form-control-lg" id="fromto">
  <option value="from">From/To</option>
  <option value="date">Exact date</option>
</select>
            <input id="dateinput" type="date" name="from" class="form-control form-control-lg" value="{{ request.GET.from }}">
            <input id="dateinput" type="date" name="to" class="form-control form-control-lg" value="{{ request.GET.to }}">
            <button type="submit" class="btn-lg btn-dark">Search</button>
        </form>
    </div>
    <div class="d-flex pt-5 justify-content-center">
        {% if object_list %}
            <div class="table-responsive">
                <table class="table">
                    <thead class="thead-dark">
                    <tr>
                        <th>Purchase date</th>
                        <th>Item</th>
                        <th>From</th>
                        <th>Quantity</th>
                        <th>Price</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>


                    {% for obj in object_list %}
                        <tr>
                            <td><a href='{{ obj.get_absolute_url }}'>{{ obj.slip.purchase_date }}</a></td>
                            <td>{{ obj.item_name}}</td>
                            <td>{{ obj.slip.seller_name }}</td>
                            <td>{{ obj.quantity }}</td>
                            <td>{{ obj.price }}</td>
                            <td>
                                <a href="{% url 'item_edit' obj.pk %}"><i class="fas fa-edit fa-lg"></i></a>
                                <a href="{% url 'item_delete' obj.pk %}"><i class="fas fa-trash-alt fa-lg"></i></a>
                            </td>
                        </tr>
                    {% endfor %}
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td><strong>{{ total_amount_sum }}</strong><br>spent in total</td>
                        </tr>
                </table>
            </div>

        {% else %}
            <div class="alert alert-warning">
                <strong>Sorry!</strong> There is no results matching your query. Try again.
            </div>
        {% endif %}
    </div>
{% endblock %}

sliply/templates/sliply/slip_confirm_delete.html
{% extends 'subbase.html' %}
{% block cardheader %}
    <a href="{% url 'slip_edit' object.pk %}"><i class="fas fa-edit fa-lg"></i></a>
{% endblock %}
{% block form %}
    <div class="col">
        <div class="alert alert-warning">Are you sure you want to delete "{{ object }}"?
            <form action="" method="post">{% csrf_token %}
                <button type="submit" class="btn btn-warning btn-lg" value="Confirm">Confirm</button>
                <input type="button" onclick="goBack()" class="btn btn-secondary btn-lg" value="Cancel">

            </form>
        </div>
{% endblock %}

sliply/templates/sliply/slip_detail.html
{% extends 'subbase.html' %}
{% block cardheader %}

    <a href="{% url 'slip_edit' object.pk %}"><i class="fas fa-edit fa-lg"></i></a>
    <a href="{% url 'slip_delete' object.pk %}"><i class="fas fa-trash-alt fa-lg"></i></a>
{% endblock %}
{% block form %}
    <div class="col">
        <div class="row">
            Purchase date: {{ object.purchase_date }}
        </div>
        <div class="row">
            From: {{ object.seller_name }}
        </div>
        <div class="row">
            Total amount: {{ object.total_amount }}
        </div>
        <div class="row">
            Paid by: {{ object.get_payment_type_display }}
        </div>
        {% if object.item_set.all %}
            <div class="row">
                <strong>Items:</strong>

                <ol>
                    {% for obj in object.item_set.all %}
                        <li><a href="{% url 'item_details' obj.pk %}">{{ obj.item_name }}</a></li>

                    {% endfor %}
                </ol>
            </div>
        {% endif %}
        {% if object.scanfile %}
            <a href="{{ path|default:"/media/" }}{{ object.scanfile }}"><img
                    src="{{ path|default:"/media/" }}{{ object.scanfile }}"
                    style="width: 15vw"></a>
        {% endif %}
        <p><br><a class="btn btn-info" role="button" href="{% url 'slip_details' object.pk %}?action=rescan">Rescan</a>
        </p>

    </div>

{% endblock %}

sliply/templates/sliply/slip_form.html
{% extends 'subbase.html' %}
{% block cardheader %}
    <a href="{% url 'slip_edit' object.pk %}"><i class="fas fa-edit fa-lg"></i></a>
    <a href="{% url 'slip_delete' object.pk %}"><i class="fas fa-trash-alt fa-lg"></i></a>
{% endblock %}
{% block form %}
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>

{% endblock %}

sliply/templates/sliply/slip_list.html
{% extends 'base.html' %}
{% block content %}
    <div class="d-flex pt-5 justify-content-center">
        <form action="{% url 'slips_search' %}" class="form-inline">
            <input type="text" id="searchinput" name="query" class="form-control form-control-lg"
                   placeholder="Search"
                   value="{{ request.GET.query }}">
            <select name="fromto" class="form-control form-control-lg" id="fromto">
  <option value="from">From/To</option>
  <option value="date">Exact date</option>
</select>
            <input id="dateinput" type="date" name="from" class="form-control form-control-lg" value="{{ request.GET.from }}">
            <input id="dateinput" type="date" name="to" class="form-control form-control-lg" value="{{ request.GET.to }}">
            <button type="submit" class="btn-lg btn-dark">Search</button>
        </form>
    </div>
    <div class="d-flex pt-5 justify-content-center">
        {% if object_list %}
            <div class="table-responsive">
                <table class="table">
                    <thead class="thead-dark">
                    <tr>
                        <th>Purchase date</th>
                        <th>From</th>
                        <th>Total amount</th>
                        <th>Payment type</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>


                    {% for obj in object_list %}
                        {% if obj.purchase_date != None %}
                        <tr>
                            <td><a href='{{ obj.get_absolute_url }}'>{{ obj.purchase_date }}</a></td>
                            <td>{{ obj.seller_name}}</td>
                            <td>{{ obj.total_amount }}</td>
                            <td>{{ obj.get_payment_type_display }}</td>
                            <td>
                                <a href="{% url 'slip_edit' obj.pk %}"><i class="fas fa-edit fa-lg"></i></a>
                                <a href="{% url 'slip_delete' obj.pk %}"><i class="fas fa-trash-alt fa-lg"></i></a>
                            </td>
                        </tr>
                        {% else %}

                        <tr>
                            <td>Text recognition in progress...</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td>
                            </td>
                        </tr>
                        {% endif %}
                    {% endfor %}
                       <tr>
                            <td></td>
                            <td></td>
                            <td><strong>{{ total_amount_sum }}</strong><br>spent in total</td>
                            <td></td>
                            <td></td>
                        </tr>
                </table>
            </div>

        {% else %}
            <div class="alert alert-warning">
                <strong>Sorry!</strong> There is no results matching your query. Try again.
            </div>
        {% endif %}
    </div>
{% endblock %}